export const paths = [
  // ===== DOCTOR: EGYPT NATIONAL TRACKS =====
  { name: 'Stay-Egypt (MOH Government Track)', category: 'doctor', path_type: 'career', target_country: 'Egypt',
    description: 'Ministry of Health hospital placement — government salary scale, pension, and job security.',
    required_exams: [{ name: 'Egyptian Medical Licensing Exam', official_link: 'https://www.ems.org.eg', format: 'written', cost_usd: 200, retake_policy: 'Unlimited attempts, 3-month waiting period' }],
    required_language_tests: [], total_estimated_cost_usd: 500, total_duration_months: 48,
    content_status: 'verified', order: 1,
    official_source_links: ['https://www.ems.org.eg'], egypt_specific_notes: 'Requires MBBS from an Egyptian university or equivalency from the Supreme Council of Universities.' },
  { name: 'Stay-Egypt (University Hospital Track)', category: 'doctor', path_type: 'career', target_country: 'Egypt',
    description: 'Teaching hospital appointment with path toward Masters/MD/professorship — research-adjacent academic career.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 2,
    official_source_links: [], egypt_specific_notes: 'Typically requires Master\'s degree pathway alongside clinical appointment.' },
  { name: 'Stay-Egypt (Private Sector Practice)', category: 'doctor', path_type: 'career', target_country: 'Egypt',
    description: 'Private hospital or own clinic — income-driven career with less job security than government positions.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 3,
    official_source_links: [], egypt_specific_notes: 'Requires Egyptian Medical Syndicate registration. Income varies significantly by specialty and location.' },
  { name: 'Stay-Egypt (Military/Police Medical Services)', category: 'doctor', path_type: 'career', target_country: 'Egypt',
    description: 'Armed forces or police medical corps track — distinct entry process, service commitment, and benefits.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 4,
    official_source_links: [], egypt_specific_notes: 'Requires completion of military medical training program. Service commitment varies.' },
  { name: 'Stay-Egypt (Postgraduate Degree Track)', category: 'doctor', path_type: 'career', target_country: 'Egypt',
    description: 'Pursuing Egyptian Board, Masters, or MD as the primary next step before deciding clinical career direction.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 5,
    official_source_links: [], egypt_specific_notes: 'Egyptian universities offer Masters and MD programs with thesis and clinical components.' },
  { name: 'Stay-Egypt (NGO/International Health In-Country)', category: 'doctor', path_type: 'career', target_country: 'Egypt',
    description: 'Working with international organizations operating inside Egypt — WHO country office, MSF missions, UNICEF health programs.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 6,
    official_source_links: [], egypt_specific_notes: 'Usually requires MPH or relevant experience. Competitive, often contract-based.' },

  // ===== DOCTOR: GULF =====
  { name: 'Saudi Arabia — Prometric/SCFHS', category: 'doctor', path_type: 'migration', target_country: 'Saudi Arabia',
    description: 'Saudi Commission for Health Specialties (SCFHS) licensing via the Prometric exam — the main pathway for Egyptian doctors to work in Saudi Arabia.',
    required_exams: [{ name: 'Saudi Medical Licensing Exam (SMLE)', official_link: 'https://www.scfhs.org.sa', format: 'computer', cost_usd: 400, retake_policy: 'Max 4 attempts per year' }],
    required_language_tests: [{ language: 'English', test_name: 'IELTS', min_score: '6.0', official_link: 'https://www.ielts.org' }],
    total_estimated_cost_usd: 2000, total_duration_months: 12,
    content_status: 'verified', order: 7,
    official_source_links: ['https://www.scfhs.org.sa'], egypt_specific_notes: 'Egyptian degrees are recognized by SCFHS. Dataflow verification required.' },
  { name: 'UAE — DHA (Dubai)', category: 'doctor', path_type: 'migration', target_country: 'UAE',
    description: 'Dubai Health Authority licensing for medical practice in Dubai — growing hub with high demand for Egyptian specialists.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 8,
    official_source_links: ['https://www.dha.gov.ae'], egypt_specific_notes: 'Primary Source Verification (PSV) required through Dataflow.' },
  { name: 'UAE — MOH/Haad (Abu Dhabi)', category: 'doctor', path_type: 'migration', target_country: 'UAE',
    description: 'Department of Health Abu Dhabi (formerly HAAD) licensing for practice in Abu Dhabi and Northern Emirates.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 9,
    official_source_links: ['https://www.doh.gov.ae'], egypt_specific_notes: 'Similar PSV Dataflow process. Typically requires a written exam.' },
  { name: 'Qatar — QCHP', category: 'doctor', path_type: 'migration', target_country: 'Qatar',
    description: 'Qatar Council for Healthcare Practitioners licensing — growing healthcare sector with World Cup legacy infrastructure.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 10,
    official_source_links: ['https://www.qchp.org.qa'], egypt_specific_notes: 'Prometric-based exam with dataflow verification.' },
  { name: 'Kuwait — MOH Licensing', category: 'doctor', path_type: 'migration', target_country: 'Kuwait',
    description: 'Kuwait Ministry of Health licensing for medical practice — established destination for Egyptian doctors.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 11,
    official_source_links: [], egypt_specific_notes: 'Requires credential verification and Kuwait MOH written exam for some specialities.' },
  { name: 'Bahrain — NHRA', category: 'doctor', path_type: 'migration', target_country: 'Bahrain',
    description: 'National Health Regulatory Authority licensing for medical practice in Bahrain.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 12,
    official_source_links: ['https://www.nhra.bh'], egypt_specific_notes: 'Smaller job market but faster processing times than Saudi/UAE.' },
  { name: 'Oman — MOH Licensing', category: 'doctor', path_type: 'migration', target_country: 'Oman',
    description: 'Oman Ministry of Health licensing — emerging destination with growing healthcare investment.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 13,
    official_source_links: [], egypt_specific_notes: 'Prometric exam typically required. Growing demand for specialists.' },

  // ===== DOCTOR: EUROPE =====
  { name: 'UK — PLAB', category: 'doctor', path_type: 'migration', target_country: 'United Kingdom',
    description: 'UK medical licensing via PLAB 1 and PLAB 2, then GMC registration — the most popular European route for Egyptian graduates.',
    required_exams: [
      { name: 'PLAB 1', official_link: 'https://www.gmc-uk.org', format: 'computer', cost_usd: 300, retake_policy: 'Max 4 attempts' },
      { name: 'PLAB 2', official_link: 'https://www.gmc-uk.org', format: 'practical', cost_usd: 1000, retake_policy: 'Max 4 attempts' },
    ],
    required_language_tests: [
      { language: 'English', test_name: 'IELTS', min_score: '7.5', official_link: 'https://www.ielts.org' },
      { language: 'English', test_name: 'OET Medicine', min_score: 'B', official_link: 'https://www.oet.com' },
    ],
    total_estimated_cost_usd: 4000, total_duration_months: 18,
    content_status: 'verified', order: 14,
    official_source_links: ['https://www.gmc-uk.org'], egypt_specific_notes: 'Egyptian MBBS recognized by GMC. Foundation year 2 (FY2) equivalence often required.' },
  { name: 'Ireland — IMC Registration', category: 'doctor', path_type: 'migration', target_country: 'Ireland',
    description: 'Irish Medical Council registration via Certificate of Experience — growing destination with strong Egyptian doctor community.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 15,
    official_source_links: ['https://www.medicalcouncil.ie'], egypt_specific_notes: 'English-friendly. EU/EEA exemption issues affect non-EU graduates.' },
  { name: 'Germany — Approbation', category: 'doctor', path_type: 'migration', target_country: 'Germany',
    description: 'German medical licensing (Approbation) — requires German B2/C1 proficiency, growing demand for international doctors.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 16,
    official_source_links: [], egypt_specific_notes: 'Language-gated (German B2/C1 required). EQF level verification and knowledge exam usually needed.' },
  { name: 'Malta — Medical Council Registration', category: 'doctor', path_type: 'migration', target_country: 'Malta',
    description: 'Maltese medical licensing — smaller market with English-friendly environment and growing Egyptian presence.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 17,
    official_source_links: [], egypt_specific_notes: 'English is an official language. Generally faster process than UK/Germany.' },

  // ===== DOCTOR: NORTH AMERICA =====
  { name: 'USA — USMLE', category: 'doctor', path_type: 'migration', target_country: 'USA',
    description: 'US medical licensing via USMLE Steps 1-3, plus ECFMG certification for IMGs — highest-stakes, highest-reward pathway.',
    required_exams: [
      { name: 'USMLE Step 1', official_link: 'https://www.usmle.org', format: 'computer', cost_usd: 1000, retake_policy: 'Max 3 attempts per year' },
      { name: 'USMLE Step 2 CK', official_link: 'https://www.usmle.org', format: 'computer', cost_usd: 1000, retake_policy: 'Max 3 attempts per year' },
      { name: 'USMLE Step 3', official_link: 'https://www.usmle.org', format: 'computer', cost_usd: 900, retake_policy: 'Max 3 attempts per year' },
    ],
    required_language_tests: [{ language: 'English', test_name: 'OET Medicine', min_score: '350', official_link: 'https://www.oet.com' }],
    total_estimated_cost_usd: 8000, total_duration_months: 36,
    content_status: 'verified', order: 18,
    official_source_links: ['https://www.usmle.org', 'https://www.ecfmg.org'], egypt_specific_notes: 'MBBS must be verified by ECFMG before Step 1. Egyptian graduates have high match rates in Internal Medicine and Pediatrics.' },
  { name: 'Canada — NAC/MCCQE', category: 'doctor', path_type: 'migration', target_country: 'Canada',
    description: 'Canadian medical licensing via NAC-OSCE and MCCQE Part I — competitive but growing pathway for IMGs.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 19,
    official_source_links: ['https://www.mcc.ca'], egypt_specific_notes: 'Requires MCCQE Part I and NAC-OSCE. Practice-ready assessment programs available in some provinces.' },

  // ===== DOCTOR: OCEANIA =====
  { name: 'Australia — AMC', category: 'doctor', path_type: 'migration', target_country: 'Australia',
    description: 'Australian Medical Council exams (AMC MCQ + clinical) — well-established route with strong job market for specialists.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 20,
    official_source_links: ['https://www.amc.org.au'], egypt_specific_notes: 'Competency Authority Pathway available for specialists with comparable training.' },
  { name: 'New Zealand — NZREX', category: 'doctor', path_type: 'migration', target_country: 'New Zealand',
    description: 'New Zealand Registration Exam (NZREX) for IMGs — smaller market but streamlined pathway.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 21,
    official_source_links: ['https://www.mcnz.org.nz'], egypt_specific_notes: 'NZREX Clinical exam required. Competent Authority pathway available for some qualifications.' },

  // ===== DOCTOR: ADMIN/GLOBAL HEALTH =====
  { name: 'International Organization Track (WHO/UN)', category: 'doctor', path_type: 'migration', target_country: 'Global/Multiple',
    description: 'Public health and policy roles with WHO, UNICEF, UNFPA, and other UN agencies — usually requires MPH or global health experience.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 22,
    official_source_links: ['https://www.who.int/careers'], egypt_specific_notes: 'Not exam-gated. Requires MPH, relevant experience, and UN language proficiency.' },
  { name: 'Humanitarian Field Track (MSF, IRC, Red Cross)', category: 'doctor', path_type: 'migration', target_country: 'Global/Multiple',
    description: 'Field medical roles in humanitarian response — crisis medicine, emergency surgery, and public health in conflict/disaster zones.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 23,
    official_source_links: ['https://www.msf.org/work-msf'], egypt_specific_notes: 'Requires clinical experience, language skills (French/Arabic valuable), and willingness to work in insecure environments.' },
  { name: 'Global Health Research Track', category: 'doctor', path_type: 'migration', target_country: 'Global/Multiple',
    description: 'Research positions with international universities and institutes — publication-driven, often PhD or MPH pathway.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 24,
    official_source_links: [], egypt_specific_notes: 'Research experience and publications are key. Often requires MPH, MSc, or PhD.' },
  { name: 'Health-Tech / Digital Health Industry Track', category: 'doctor', path_type: 'migration', target_country: 'Global/Multiple',
    description: 'Clinical roles inside health-tech companies — telemedicine platforms, health AI, clinical decision support — growing alternative to classic migration.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 25,
    official_source_links: [], egypt_specific_notes: 'Remote-friendly. Clinical experience valued. Product management or informatics skills advantageous.' },
  { name: 'Pharmaceutical / Clinical Research Industry Track', category: 'doctor', path_type: 'migration', target_country: 'Global/Multiple',
    description: 'Medical affairs, clinical research associate, or pharmacovigilance roles with multinational pharma — often Egypt/Gulf-based.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 26,
    official_source_links: [], egypt_specific_notes: 'Egypt and UAE are regional hubs for pharma companies. Clinical research experience and GCP certification valuable.' },

  // ===== NURSE: EGYPT NATIONAL TRACKS =====
  { name: 'Stay-Egypt (MOH Government Nursing Track)', category: 'nurse', path_type: 'career', target_country: 'Egypt',
    description: 'Ministry of Health hospital nursing placement — government salary scale with pension and job security.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 1,
    official_source_links: [], egypt_specific_notes: 'Requires Egyptian Nursing Syndicate registration. Government hospitals across all governorates.' },
  { name: 'Stay-Egypt (University/Teaching Hospital Nursing Track)', category: 'nurse', path_type: 'career', target_country: 'Egypt',
    description: 'Academic hospital nursing position with path toward nursing education and faculty roles.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 2,
    official_source_links: [], egypt_specific_notes: 'Typically requires Bachelor\'s in Nursing. Teaching hospitals in major cities (Cairo, Alexandria).' },
  { name: 'Stay-Egypt (Private Sector Nursing)', category: 'nurse', path_type: 'career', target_country: 'Egypt',
    description: 'Private hospital nursing in Egypt — generally higher pay than government but less job security.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 3,
    official_source_links: [], egypt_specific_notes: 'Private hospitals concentrated in Cairo, Alexandria, and tourist areas.' },
  { name: 'Stay-Egypt (Military/Police Nursing Services)', category: 'nurse', path_type: 'career', target_country: 'Egypt',
    description: 'Armed forces or police medical corps nursing track — distinct entry, benefits, and service commitment.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 4,
    official_source_links: [], egypt_specific_notes: 'Requires military/security clearance. Service commitment and benefits differ from civilian tracks.' },
  { name: 'Stay-Egypt (Postgraduate Nursing Track)', category: 'nurse', path_type: 'career', target_country: 'Egypt',
    description: 'Pursuing a Master\'s in Nursing or nursing specialization in Egypt as the next career step.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 5,
    official_source_links: [], egypt_specific_notes: 'Egyptian universities offer Master\'s in Nursing with clinical and thesis components.' },
  { name: 'Stay-Egypt (NGO/International Health Nursing)', category: 'nurse', path_type: 'career', target_country: 'Egypt',
    description: 'Working with international health organizations operating inside Egypt — WHO, UNICEF, UNFPA nursing programs.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 6,
    official_source_links: [], egypt_specific_notes: 'Relevant experience and English proficiency important. Contract-based, competitive positions.' },

  // ===== NURSE: GULF =====
  { name: 'Saudi Arabia — Saudi Nursing License (SCFHS)', category: 'nurse', path_type: 'migration', target_country: 'Saudi Arabia',
    description: 'Saudi Commission for Health Specialties nursing licensing via Prometric — the largest overseas destination for Egyptian nurses.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 7,
    official_source_links: ['https://www.scfhs.org.sa'], egypt_specific_notes: 'Prometric exam for nursing. Dataflow verification required. Arabic language sometimes required for patient-facing roles.' },
  { name: 'UAE — Nursing License (DHA/DoH)', category: 'nurse', path_type: 'migration', target_country: 'UAE',
    description: 'Dubai Health Authority or Department of Health Abu Dhabi licensing for nursing practice in the UAE.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 8,
    official_source_links: ['https://www.dha.gov.ae'], egypt_specific_notes: 'Primary Source Verification required. Written exam for licensing.' },

  // ===== NURSE: EUROPE =====
  { name: 'UK — NMC OSCE', category: 'nurse', path_type: 'migration', target_country: 'United Kingdom',
    description: 'UK nursing registration via NMC — CBT + OSCE, the most popular European route for Egyptian nurses.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 9,
    official_source_links: ['https://www.nmc.org.uk'], egypt_specific_notes: 'IELTS 7.0 or OET B required. CBT followed by OSCE in UK. Growing NHS recruitment from Egypt.' },
  { name: 'Ireland — NMBI Registration', category: 'nurse', path_type: 'migration', target_country: 'Ireland',
    description: 'Nursing and Midwifery Board of Ireland (NMBI) registration — English-friendly alternative to UK.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 10,
    official_source_links: ['https://www.nmbi.ie'], egypt_specific_notes: 'IELTS/OET requirement. Competency assessment and adaptation period may be required.' },
  { name: 'Germany — Nursing Approbation', category: 'nurse', path_type: 'migration', target_country: 'Germany',
    description: 'German nursing licensing (Approbation) — requires German B1/B2, growing recruitment from Egypt.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 11,
    official_source_links: [], egypt_specific_notes: 'German B1/B2 certification required. Recognition procedure for foreign nursing qualifications.' },
  { name: 'Malta — Nursing Council Registration', category: 'nurse', path_type: 'migration', target_country: 'Malta',
    description: 'Maltese nursing registration — English-friendly, smaller but accessible market.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 12,
    official_source_links: [], egypt_specific_notes: 'English language requirement. Smaller job market but faster process than UK/Germany.' },

  // ===== NURSE: NORTH AMERICA =====
  { name: 'Canada — NCLEX-RN', category: 'nurse', path_type: 'migration', target_country: 'Canada',
    description: 'Canadian nursing licensing via NCLEX-RN, plus NNAS assessment for Internationally Educated Nurses (IENs).',
    required_exams: [
      { name: 'NCLEX-RN', official_link: 'https://www.ncsbn.org/nclex.htm', format: 'computer', cost_usd: 400, retake_policy: 'Max 8 attempts per year' },
      { name: 'Jurisprudence Exam', official_link: 'https://www.cno.org', format: 'online', cost_usd: 100, retake_policy: 'Unlimited' },
    ],
    required_language_tests: [{ language: 'English', test_name: 'IELTS Academic', min_score: '7.0', official_link: 'https://www.ielts.org' }],
    total_estimated_cost_usd: 5000, total_duration_months: 24,
    content_status: 'verified', order: 13,
    official_source_links: ['https://www.nnas.ca', 'https://www.cno.org'], egypt_specific_notes: 'NNAS assessment required for Egyptian nursing diplomas. Bridging programs often needed for clinical hours equivalence.' },
  { name: 'USA — NCLEX-RN', category: 'nurse', path_type: 'migration', target_country: 'USA',
    description: 'US nursing licensing via NCLEX-RN — the highest-paying destination for Egyptian nurses.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 14,
    official_source_links: ['https://www.ncsbn.org/nclex.htm'], egypt_specific_notes: 'CGFNS or equivalent credentials evaluation required. VisaScreen certification needed for work visa.' },

  // ===== NURSE: OCEANIA =====
  { name: 'Australia — AHPRA/ANMAC Nursing', category: 'nurse', path_type: 'migration', target_country: 'Australia',
    description: 'Australian nursing registration via AHPRA — skilled migration pathway with strong demand across all states.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 15,
    official_source_links: ['https://www.ahpra.gov.au'], egypt_specific_notes: 'ANMAC skills assessment required. IELTS 7.0 or OET B. Bridging programs may be needed.' },
  { name: 'New Zealand — Nursing Council Registration', category: 'nurse', path_type: 'migration', target_country: 'New Zealand',
    description: 'New Zealand nursing registration — streamlined pathway for IENs with growing healthcare workforce needs.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 16,
    official_source_links: ['https://www.nursingcouncil.org.nz'], egypt_specific_notes: 'Competency assessment program (CAP) may be required. IELTS 7.0.' },

  // ===== NURSE: ADMIN/GLOBAL HEALTH =====
  { name: 'International Organization Nursing (WHO/UN)', category: 'nurse', path_type: 'migration', target_country: 'Global/Multiple',
    description: 'Nursing advisory and program management roles with WHO, UNICEF, UNFPA — public health focus.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 17,
    official_source_links: ['https://www.who.int/careers'], egypt_specific_notes: 'MPH or relevant experience. Not exam-gated. Usually requires UN language proficiency.' },
  { name: 'Humanitarian Nursing (MSF, IRC, Red Cross)', category: 'nurse', path_type: 'migration', target_country: 'Global/Multiple',
    description: 'Field nursing in humanitarian settings — emergency response, primary care, and public health in crisis zones.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 18,
    official_source_links: ['https://www.msf.org/work-msf'], egypt_specific_notes: 'Clinical experience, language skills, and willingness to work in insecure environments required.' },
  { name: 'Global Health Research Nursing', category: 'nurse', path_type: 'migration', target_country: 'Global/Multiple',
    description: 'Research nursing roles with international health research institutes — clinical trials, epidemiological studies, and implementation research.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 19,
    official_source_links: [], egypt_specific_notes: 'Research nursing and GCP (Good Clinical Practice) certification valuable.' },
  { name: 'Health-Tech Nursing / Nursing Informatics', category: 'nurse', path_type: 'migration', target_country: 'Global/Multiple',
    description: 'Clinical informatics and health-tech roles for nurses — EHR implementation, telehealth, and clinical product management.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 20,
    official_source_links: [], egypt_specific_notes: 'Informatics experience and EHR knowledge valuable. Remote-friendly career.' },
  { name: 'Pharmaceutical/Clinical Research Nursing', category: 'nurse', path_type: 'migration', target_country: 'Global/Multiple',
    description: 'Clinical research nursing roles within pharmaceutical companies — clinical trial coordination and pharmacovigilance.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 21,
    official_source_links: [], egypt_specific_notes: 'GCP certification required. Regional pharma hubs in Egypt and UAE.' },
  // ===== DOCTOR: UK ROYAL COLLEGE TRAINING PATHS =====
  { name: 'UK — MRCP (Internal Medicine)', category: 'doctor', path_type: 'training', target_country: 'United Kingdom',
    description: 'Membership of the Royal College of Physicians — the professional qualification for physicians in the UK, required for specialty training in Internal Medicine and its sub-specialties.',
    stages: [
      { name: 'Foundation Training (FY1-FY2)', type: 'foundation', order: 1, duration_months: 24, description: 'Two-year foundation programme after medical school, with rotations across medical and surgical specialties.', prerequisites: ['MBBS or equivalent primary medical qualification'] },
      { name: 'Internal Medicine Training (IMT1-IMT3)', type: 'training_post', order: 2, duration_months: 36, description: 'Core medical training with exposure to acute medicine, specialties, and out-patient clinics.', cost_usd: 500, prerequisites: ['Foundation Year completion', 'GMC registration with licence to practise'] },
      { name: 'MRCP Part 1', type: 'exam', order: 3, duration_months: 6, description: '200-question multiple-choice exam covering basic sciences relevant to medical practice.', cost_usd: 500, exams: [{ name: 'MRCP Part 1', format: 'computer', cost_usd: 500, official_link: 'https://www.mrcpuk.org' }] },
      { name: 'MRCP Part 2', type: 'exam', order: 4, duration_months: 6, description: '200-question multiple-choice exam covering clinical medicine.', cost_usd: 550, exams: [{ name: 'MRCP Part 2 Written', format: 'computer', cost_usd: 550, official_link: 'https://www.mrcpuk.org' }] },
      { name: 'MRCP PACES', type: 'exam', order: 5, duration_months: 6, description: 'Practical Assessment of Clinical Examination Skills — a five-station OSCE assessing clinical examination, communication, and diagnosis.', cost_usd: 1200, exams: [{ name: 'MRCP PACES', format: 'practical', cost_usd: 1200, official_link: 'https://www.mrcpuk.org' }] },
      { name: 'Specialty Training (ST3-ST7)', type: 'training_post', order: 6, duration_months: 60, description: 'Advanced training in chosen internal medicine sub-specialty (cardiology, gastroenterology, respiratory, etc.).', prerequisites: ['MRCP full diploma', 'GMC registration'] },
      { name: 'Certificate of Completion of Training (CCT)', type: 'application', order: 7, description: 'Final certification confirming completion of specialty training, enabling specialist registration with the GMC.', prerequisites: ['Completion of ST6+', 'MRCP diploma', 'ARCP sign-off'] },
    ],
    total_estimated_cost_usd: 3500, total_duration_months: 96,
    content_status: 'verified', order: 27,
    official_source_links: ['https://www.mrcpuk.org', 'https://www.jrcptb.org.uk'], egypt_specific_notes: 'This is the UK graduate training route. Egyptian IMGs typically take the PLAB route first, then apply for equivalence.' },

  { name: 'UK — MRCS (Surgery)', category: 'doctor', path_type: 'training', target_country: 'United Kingdom',
    description: 'Membership of the Royal College of Surgeons — the gateway qualification for all surgical specialties (general surgery, orthopaedics, ENT, urology, etc.).',
    stages: [
      { name: 'Foundation Training (FY1-FY2)', type: 'foundation', order: 1, duration_months: 24, description: 'Two-year foundation programme with surgical rotations.', prerequisites: ['MBBS or equivalent'] },
      { name: 'Core Surgical Training (CT1-CT2)', type: 'training_post', order: 2, duration_months: 24, description: 'Two-year programme in basic surgical skills, emergency surgery, and theatre experience.', cost_usd: 500, prerequisites: ['Foundation completion', 'GMC registration'] },
      { name: 'MRCS Part A', type: 'exam', order: 3, duration_months: 6, description: 'Applied basic sciences and principles of surgery in written format.', cost_usd: 450, exams: [{ name: 'MRCS Part A', format: 'computer', cost_usd: 450, official_link: 'https://www.rcseng.ac.uk' }] },
      { name: 'MRCS Part B (OSCE)', type: 'exam', order: 4, duration_months: 6, description: 'Objective Structured Clinical Examination testing surgical skills, anatomy, and communication.', cost_usd: 1000, exams: [{ name: 'MRCS Part B', format: 'practical', cost_usd: 1000, official_link: 'https://www.rcseng.ac.uk' }] },
      { name: 'Specialty Training (ST3-ST8)', type: 'training_post', order: 5, duration_months: 72, description: 'Higher surgical training in chosen specialty (general surgery, orthopaedics, neurosurgery, etc.).', prerequisites: ['MRCS diploma', 'Core Surgical Training completion'] },
      { name: 'Certificate of Completion of Training (CCT)', type: 'application', order: 6, description: 'Final certification as a consultant surgeon.', prerequisites: ['ST8 completion', 'MRCS', 'ARCP sign-off'] },
    ],
    total_estimated_cost_usd: 3000, total_duration_months: 108,
    content_status: 'verified', order: 28,
    official_source_links: ['https://www.rcseng.ac.uk', 'https://www.iscp.ac.uk'], egypt_specific_notes: 'UK surgical training pathway for UK graduates. IMGs should pursue PLAB then apply for equivalency.' },

  { name: 'UK — MRCPCH (Paediatrics)', category: 'doctor', path_type: 'training', target_country: 'United Kingdom',
    description: 'Membership of the Royal College of Paediatrics and Child Health — the specialist qualification for paediatric training in the UK.',
    stages: [
      { name: 'Foundation Training (FY1-FY2)', type: 'foundation', order: 1, duration_months: 24, description: 'Foundation programme with paediatric rotations.', prerequisites: ['MBBS'] },
      { name: 'Paediatric Specialty Training (ST1-ST2)', type: 'training_post', order: 2, duration_months: 24, description: 'Core paediatric training in general paediatrics and neonatal care.', cost_usd: 400 },
      { name: 'MRCPCH Part 1 (Foundation of Practice)', type: 'exam', order: 3, duration_months: 6, description: 'Written exam covering basic sciences and clinical paediatrics.', cost_usd: 450, exams: [{ name: 'MRCPCH Foundation of Practice', format: 'computer', cost_usd: 450, official_link: 'https://www.rcpch.ac.uk' }] },
      { name: 'MRCPCH Part 2 (Theory and Science)', type: 'exam', order: 4, duration_months: 6, description: 'Applied clinical knowledge and evidence-based paediatrics.', cost_usd: 500, exams: [{ name: 'MRCPCH Theory and Science', format: 'computer', cost_usd: 500, official_link: 'https://www.rcpch.ac.uk' }] },
      { name: 'MRCPCH Clinical Examination', type: 'exam', order: 5, duration_months: 6, description: 'Practical clinical examination assessing paediatric assessment skills.', cost_usd: 1100, exams: [{ name: 'MRCPCH Clinical', format: 'practical', cost_usd: 1100, official_link: 'https://www.rcpch.ac.uk' }] },
      { name: 'Specialty Training (ST3-ST8)', type: 'training_post', order: 6, duration_months: 72, description: 'Advanced training in paediatric sub-specialties (neonatology, cardiology, neurology, etc.).', prerequisites: ['MRCPCH', 'GMC registration'] },
      { name: 'CCT in Paediatrics', type: 'application', order: 7, description: 'Certificate of Completion of Training.', prerequisites: ['ST8 completion', 'MRCPCH'] },
    ],
    total_estimated_cost_usd: 3500, total_duration_months: 108,
    content_status: 'verified', order: 29,
    official_source_links: ['https://www.rcpch.ac.uk'], egypt_specific_notes: 'UK paediatric training pathway. IMGs require GMC registration via PLAB first.' },

  { name: 'UK — MRCGP (General Practice)', category: 'doctor', path_type: 'training', target_country: 'United Kingdom',
    description: 'Membership of the Royal College of General Practitioners — the qualification for UK general practice (family medicine).',
    stages: [
      { name: 'Foundation Training (FY1-FY2)', type: 'foundation', order: 1, duration_months: 24, description: 'Foundation programme with GP and community rotations.', prerequisites: ['MBBS'] },
      { name: 'GP Specialty Training (GPST1-GPST3)', type: 'training_post', order: 2, duration_months: 36, description: 'Three-year programme with 18 months in GP practice and 18 months in hospital posts.', cost_usd: 500, prerequisites: ['Foundation completion', 'GMC registration'] },
      { name: 'MRCGP Applied Knowledge Test (AKT)', type: 'exam', order: 3, duration_months: 6, description: '200-question MCQ testing clinical knowledge applied to primary care.', cost_usd: 450, exams: [{ name: 'MRCGP AKT', format: 'computer', cost_usd: 450, official_link: 'https://www.rcgp.org.uk' }] },
      { name: 'MRCGP Clinical Skills Assessment (CSA)', type: 'exam', order: 4, duration_months: 6, description: 'OSCE-style assessment of consultation skills across 13 cases.', cost_usd: 1200, exams: [{ name: 'MRCGP CSA', format: 'practical', cost_usd: 1200, official_link: 'https://www.rcgp.org.uk' }] },
      { name: 'MRCGP Record of Competence (RCA)', type: 'exam', order: 5, duration_months: 6, description: 'Workplace-based assessment portfolio demonstrating competence across GP curriculum.', cost_usd: 500, exams: [{ name: 'MRCGP RCA', format: 'portfolio', cost_usd: 500, official_link: 'https://www.rcgp.org.uk' }] },
      { name: 'CCT in General Practice', type: 'application', order: 6, description: 'Certificate of Completion of Training — enables entry onto the GP Register with the GMC.', prerequisites: ['GPST3 completion', 'AKT', 'CSA', 'RCA'] },
    ],
    total_estimated_cost_usd: 3500, total_duration_months: 60,
    content_status: 'verified', order: 30,
    official_source_links: ['https://www.rcgp.org.uk'], egypt_specific_notes: 'UK GP training route. IMGs need GMC registration. MRCGP is recognised in some Commonwealth countries.' },

  { name: 'UK — MRCPath (Pathology)', category: 'doctor', path_type: 'training', target_country: 'United Kingdom',
    description: 'Membership/Fellowship of the Royal College of Pathologists — for histopathology, haematology, microbiology, chemical pathology, and forensic pathology.',
    stages: [
      { name: 'Foundation Training (FY1-FY2)', type: 'foundation', order: 1, duration_months: 24, description: 'Foundation programme with laboratory medicine exposure.', prerequisites: ['MBBS'] },
      { name: 'Specialty Training (ST1)', type: 'training_post', order: 2, duration_months: 12, description: 'Introductory year in pathology with rotations across labs.', prerequisites: ['Foundation completion'] },
      { name: 'FRCPath Part 1', type: 'exam', order: 3, duration_months: 12, description: 'Written exam covering basic pathology sciences and principles.', cost_usd: 600, exams: [{ name: 'FRCPath Part 1', format: 'computer', cost_usd: 600, official_link: 'https://www.rcpath.org' }] },
      { name: 'Specialty Training (ST2-ST5)', type: 'training_post', order: 4, duration_months: 48, description: 'Intermediate and higher training in chosen pathology sub-specialty.', cost_usd: 400, prerequisites: ['FRCPath Part 1'] },
      { name: 'FRCPath Part 2', type: 'exam', order: 5, duration_months: 12, description: 'Portfolio-based assessment, practical exams, and dissertation in chosen pathology specialty.', cost_usd: 1200, exams: [{ name: 'FRCPath Part 2', format: 'practical', cost_usd: 1200, official_link: 'https://www.rcpath.org' }] },
      { name: 'CCT in Pathology', type: 'application', order: 6, description: 'Certificate of Completion of Training.', prerequisites: ['ST5 completion', 'FRCPath'] },
    ],
    total_estimated_cost_usd: 3000, total_duration_months: 108,
    content_status: 'verified', order: 31,
    official_source_links: ['https://www.rcpath.org'], egypt_specific_notes: 'UK pathology training. IMGs need GMC registration. Egypt-trained pathologists may get reduced training.' },

  { name: 'UK — FRCR (Radiology)', category: 'doctor', path_type: 'training', target_country: 'United Kingdom',
    description: 'Fellowship of the Royal College of Radiologists — for clinical radiology and clinical oncology training.',
    stages: [
      { name: 'Foundation Training (FY1-FY2)', type: 'foundation', order: 1, duration_months: 24, description: 'Foundation programme with radiology exposure.', prerequisites: ['MBBS'] },
      { name: 'Clinical Radiology Training (ST1)', type: 'training_post', order: 2, duration_months: 12, description: 'First year of radiology training with basic reporting and imaging skills.', prerequisites: ['Foundation completion'] },
      { name: 'FRCR Part 1', type: 'exam', order: 3, duration_months: 6, description: 'Physics and anatomy written examination.', cost_usd: 500, exams: [{ name: 'FRCR Part 1', format: 'computer', cost_usd: 500, official_link: 'https://www.rcr.ac.uk' }] },
      { name: 'FRCR Part 2A', type: 'exam', order: 4, duration_months: 6, description: 'Written exam covering all radiological systems and pathologies.', cost_usd: 600, exams: [{ name: 'FRCR Part 2A', format: 'computer', cost_usd: 600, official_link: 'https://www.rcr.ac.uk' }] },
      { name: 'FRCR Part 2B (Rapid Reporting + OSCE)', type: 'exam', order: 5, duration_months: 6, description: 'Practical exam: rapid reporting of 20 cases and 8 OSCE stations.', cost_usd: 1300, exams: [{ name: 'FRCR Part 2B', format: 'practical', cost_usd: 1300, official_link: 'https://www.rcr.ac.uk' }] },
      { name: 'Advanced Training (ST5-ST7)', type: 'training_post', order: 6, duration_months: 36, description: 'Sub-specialty training in neuroradiology, interventional radiology, paediatrics, etc.', prerequisites: ['FRCR', 'ST1-ST4 completion'] },
      { name: 'CCT in Clinical Radiology', type: 'application', order: 7, description: 'Certificate of Completion of Training.', prerequisites: ['ST7 completion', 'FRCR'] },
    ],
    total_estimated_cost_usd: 3500, total_duration_months: 108,
    content_status: 'verified', order: 32,
    official_source_links: ['https://www.rcr.ac.uk'], egypt_specific_notes: 'UK radiology training. Highly competitive. IMGs require GMC registration.' },

  { name: 'UK — FRCA (Anaesthetics)', category: 'doctor', path_type: 'training', target_country: 'United Kingdom',
    description: 'Fellowship of the Royal College of Anaesthetists — the professional qualification for anaesthesia, intensive care, and pain medicine.',
    stages: [
      { name: 'Foundation Training (FY1-FY2)', type: 'foundation', order: 1, duration_months: 24, description: 'Foundation programme with anaesthetics and ICU rotations.', prerequisites: ['MBBS'] },
      { name: 'Core Anaesthesia Training (CT1-CT2)', type: 'training_post', order: 2, duration_months: 24, description: 'Basic anaesthesia training in theatre, ICU, and emergency settings.', cost_usd: 400, prerequisites: ['Foundation completion'] },
      { name: 'Primary FRCA', type: 'exam', order: 3, duration_months: 12, description: 'MCQ and OSCE covering physics, pharmacology, physiology, and basic anaesthesia.', cost_usd: 900, exams: [{ name: 'Primary FRCA MCQ', format: 'computer', cost_usd: 450, official_link: 'https://www.rcoa.ac.uk' }, { name: 'Primary FRCA OSCE', format: 'practical', cost_usd: 450, official_link: 'https://www.rcoa.ac.uk' }] },
      { name: 'Intermediate Training (ST3-ST4)', type: 'training_post', order: 4, duration_months: 24, description: 'Advanced anaesthesia training with subspecialty exposure.', prerequisites: ['Primary FRCA', 'CT2 completion'] },
      { name: 'Final FRCA', type: 'exam', order: 5, duration_months: 12, description: 'Written and practical exam covering all aspects of anaesthesia, ICU, and pain.', cost_usd: 1000, exams: [{ name: 'Final FRCA Written', format: 'computer', cost_usd: 500, official_link: 'https://www.rcoa.ac.uk' }, { name: 'Final FRCA SOE', format: 'oral', cost_usd: 500, official_link: 'https://www.rcoa.ac.uk' }] },
      { name: 'Advanced Training (ST5-ST7)', type: 'training_post', order: 6, duration_months: 36, description: 'Higher training in anaesthesia with optional dual CCT in ICM.', prerequisites: ['Final FRCA'] },
      { name: 'CCT in Anaesthetics', type: 'application', order: 7, description: 'Certificate of Completion of Training.', prerequisites: ['ST7 completion', 'FRCA'] },
    ],
    total_estimated_cost_usd: 3500, total_duration_months: 108,
    content_status: 'verified', order: 33,
    official_source_links: ['https://www.rcoa.ac.uk'], egypt_specific_notes: 'UK anaesthetics training. IMGs should have PLAB + GMC registration first.' },

  { name: 'UK — MRCOG (Obstetrics & Gynaecology)', category: 'doctor', path_type: 'training', target_country: 'United Kingdom',
    description: 'Membership of the Royal College of Obstetricians and Gynaecologists — the specialist qualification for O&G training in the UK.',
    stages: [
      { name: 'Foundation Training (FY1-FY2)', type: 'foundation', order: 1, duration_months: 24, description: 'Foundation programme with O&G rotations.', prerequisites: ['MBBS'] },
      { name: 'Core O&G Training (ST1-ST2)', type: 'training_post', order: 2, duration_months: 24, description: 'Basic training in obstetrics, gynaecology, and reproductive medicine.', cost_usd: 400, prerequisites: ['Foundation completion'] },
      { name: 'MRCOG Part 1', type: 'exam', order: 3, duration_months: 6, description: 'Written exam covering basic sciences relevant to O&G.', cost_usd: 450, exams: [{ name: 'MRCOG Part 1', format: 'computer', cost_usd: 450, official_link: 'https://www.rcog.org.uk' }] },
      { name: 'MRCOG Part 2', type: 'exam', order: 4, duration_months: 6, description: 'Written exam on clinical O&G knowledge and evidence-based practice.', cost_usd: 550, exams: [{ name: 'MRCOG Part 2', format: 'computer', cost_usd: 550, official_link: 'https://www.rcog.org.uk' }] },
      { name: 'MRCOG OSCE', type: 'exam', order: 5, duration_months: 6, description: 'Objective Structured Clinical Examination with 8 stations.', cost_usd: 1200, exams: [{ name: 'MRCOG OSCE', format: 'practical', cost_usd: 1200, official_link: 'https://www.rcog.org.uk' }] },
      { name: 'Advanced Training (ST3-ST7)', type: 'training_post', order: 6, duration_months: 60, description: 'Sub-specialty training in maternal-fetal medicine, gynae-oncology, reproductive medicine, or urogynaecology.', prerequisites: ['MRCOG'] },
      { name: 'CCT in O&G', type: 'application', order: 7, description: 'Certificate of Completion of Training.', prerequisites: ['ST7 completion', 'MRCOG'] },
    ],
    total_estimated_cost_usd: 3500, total_duration_months: 108,
    content_status: 'verified', order: 34,
    official_source_links: ['https://www.rcog.org.uk'], egypt_specific_notes: 'UK O&G training. MRCOG is also recognised in the Middle East and Australia.' },

  { name: 'UK — MFPH (Public Health)', category: 'doctor', path_type: 'training', target_country: 'United Kingdom',
    description: 'Membership of the Faculty of Public Health — the specialist qualification for public health consultants and specialists in the UK.',
    stages: [
      { name: 'Foundation Training (FY1-FY2)', type: 'foundation', order: 1, duration_months: 24, description: 'Foundation programme (can include public health placements).', prerequisites: ['MBBS'] },
      { name: 'Public Health Specialty Training (ST1-ST4)', type: 'training_post', order: 2, duration_months: 48, description: 'Four-year training programme in public health practice, epidemiology, and health policy.', cost_usd: 500, prerequisites: ['Foundation completion', 'GMC registration', 'MFPH Part A recommended'] },
      { name: 'MFPH Part A', type: 'exam', order: 3, duration_months: 6, description: 'Written exam covering epidemiology, statistics, health economics, and public health sciences.', cost_usd: 600, exams: [{ name: 'MFPH Part A', format: 'computer', cost_usd: 600, official_link: 'https://www.fph.org.uk' }] },
      { name: 'MFPH Part B', type: 'exam', order: 4, duration_months: 12, description: 'Portfolio-based assessment including audit, research, teaching, and management competencies.', cost_usd: 800, exams: [{ name: 'MFPH Part B', format: 'portfolio', cost_usd: 800, official_link: 'https://www.fph.org.uk' }] },
      { name: 'CCT in Public Health', type: 'application', order: 5, description: 'Certificate of Completion of Training, leading to UK Specialist Register entry.', prerequisites: ['ST5 completion', 'MFPH Part A + B', 'ARCP sign-off'] },
    ],
    total_estimated_cost_usd: 2500, total_duration_months: 72,
    content_status: 'verified', order: 35,
    official_source_links: ['https://www.fph.org.uk'], egypt_specific_notes: 'Open to doctors and non-medical graduates (with relevant MSc). IMGs need GMC registration.' },

  { name: 'UK — MRCPsych (Psychiatry)', category: 'doctor', path_type: 'training', target_country: 'United Kingdom',
    description: 'Membership of the Royal College of Psychiatrists — the specialist qualification for psychiatric training in the UK.',
    stages: [
      { name: 'Foundation Training (FY1-FY2)', type: 'foundation', order: 1, duration_months: 24, description: 'Foundation programme with psychiatry placements.', prerequisites: ['MBBS'] },
      { name: 'Core Psychiatry Training (CT1-CT3)', type: 'training_post', order: 2, duration_months: 36, description: 'Three-year core training across general adult, old age, child & adolescent, forensic, and learning disability psychiatry.', cost_usd: 500, prerequisites: ['Foundation completion', 'GMC registration'] },
      { name: 'MRCPsych Part A', type: 'exam', order: 3, duration_months: 6, description: 'Written exam covering basic sciences, psychopathology, and psychiatric principles.', cost_usd: 450, exams: [{ name: 'MRCPsych Part A', format: 'computer', cost_usd: 450, official_link: 'https://www.rcpsych.ac.uk' }] },
      { name: 'MRCPsych Part B', type: 'exam', order: 4, duration_months: 6, description: 'Written exam on clinical psychiatry, treatment approaches, and evidence-based practice.', cost_usd: 550, exams: [{ name: 'MRCPsych Part B', format: 'computer', cost_usd: 550, official_link: 'https://www.rcpsych.ac.uk' }] },
      { name: 'MRCPsych CASC', type: 'exam', order: 5, duration_months: 6, description: 'Clinical Assessment of Skills and Competencies — a 12-station OSCE.', cost_usd: 1200, exams: [{ name: 'MRCPsych CASC', format: 'practical', cost_usd: 1200, official_link: 'https://www.rcpsych.ac.uk' }] },
      { name: 'Advanced Training (ST4-ST6)', type: 'training_post', order: 6, duration_months: 36, description: 'Sub-specialty training in chosen area (child, forensic, old age, psychotherapy, etc.).', prerequisites: ['MRCPsych', 'Core Training completion'] },
      { name: 'CCT in Psychiatry', type: 'application', order: 7, description: 'Certificate of Completion of Training.', prerequisites: ['ST6 completion', 'MRCPsych'] },
    ],
    total_estimated_cost_usd: 3500, total_duration_months: 96,
    content_status: 'verified', order: 36,
    official_source_links: ['https://www.rcpsych.ac.uk'], egypt_specific_notes: 'UK psychiatry training. IMGs should obtain GMC registration via PLAB. MRCPsych is highly valued internationally.' },
];
