export const paths = [
  // ===== DOCTOR: EGYPT NATIONAL TRACKS =====
  { name: 'Stay-Egypt (MOH Government Track)', category: 'doctor', target_country: 'Egypt',
    description: 'Ministry of Health hospital placement — government salary scale, pension, and job security.',
    required_exams: [{ name: 'Egyptian Medical Licensing Exam', official_link: 'https://www.ems.org.eg', format: 'written', cost_usd: 200, retake_policy: 'Unlimited attempts, 3-month waiting period' }],
    required_language_tests: [], total_estimated_cost_usd: 500, total_duration_months: 48,
    content_status: 'verified', order: 1,
    official_source_links: ['https://www.ems.org.eg'], egypt_specific_notes: 'Requires MBBS from an Egyptian university or equivalency from the Supreme Council of Universities.' },
  { name: 'Stay-Egypt (University Hospital Track)', category: 'doctor', target_country: 'Egypt',
    description: 'Teaching hospital appointment with path toward Masters/MD/professorship — research-adjacent academic career.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 2,
    official_source_links: [], egypt_specific_notes: 'Typically requires Master\'s degree pathway alongside clinical appointment.' },
  { name: 'Stay-Egypt (Private Sector Practice)', category: 'doctor', target_country: 'Egypt',
    description: 'Private hospital or own clinic — income-driven career with less job security than government positions.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 3,
    official_source_links: [], egypt_specific_notes: 'Requires Egyptian Medical Syndicate registration. Income varies significantly by specialty and location.' },
  { name: 'Stay-Egypt (Military/Police Medical Services)', category: 'doctor', target_country: 'Egypt',
    description: 'Armed forces or police medical corps track — distinct entry process, service commitment, and benefits.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 4,
    official_source_links: [], egypt_specific_notes: 'Requires completion of military medical training program. Service commitment varies.' },
  { name: 'Stay-Egypt (Postgraduate Degree Track)', category: 'doctor', target_country: 'Egypt',
    description: 'Pursuing Egyptian Board, Masters, or MD as the primary next step before deciding clinical career direction.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 5,
    official_source_links: [], egypt_specific_notes: 'Egyptian universities offer Masters and MD programs with thesis and clinical components.' },
  { name: 'Stay-Egypt (NGO/International Health In-Country)', category: 'doctor', target_country: 'Egypt',
    description: 'Working with international organizations operating inside Egypt — WHO country office, MSF missions, UNICEF health programs.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 6,
    official_source_links: [], egypt_specific_notes: 'Usually requires MPH or relevant experience. Competitive, often contract-based.' },

  // ===== DOCTOR: GULF =====
  { name: 'Saudi Arabia — Prometric/SCFHS', category: 'doctor', target_country: 'Saudi Arabia',
    description: 'Saudi Commission for Health Specialties (SCFHS) licensing via the Prometric exam — the main pathway for Egyptian doctors to work in Saudi Arabia.',
    required_exams: [{ name: 'Saudi Medical Licensing Exam (SMLE)', official_link: 'https://www.scfhs.org.sa', format: 'computer', cost_usd: 400, retake_policy: 'Max 4 attempts per year' }],
    required_language_tests: [{ language: 'English', test_name: 'IELTS', min_score: '6.0', official_link: 'https://www.ielts.org' }],
    total_estimated_cost_usd: 2000, total_duration_months: 12,
    content_status: 'verified', order: 7,
    official_source_links: ['https://www.scfhs.org.sa'], egypt_specific_notes: 'Egyptian degrees are recognized by SCFHS. Dataflow verification required.' },
  { name: 'UAE — DHA (Dubai)', category: 'doctor', target_country: 'UAE',
    description: 'Dubai Health Authority licensing for medical practice in Dubai — growing hub with high demand for Egyptian specialists.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 8,
    official_source_links: ['https://www.dha.gov.ae'], egypt_specific_notes: 'Primary Source Verification (PSV) required through Dataflow.' },
  { name: 'UAE — MOH/Haad (Abu Dhabi)', category: 'doctor', target_country: 'UAE',
    description: 'Department of Health Abu Dhabi (formerly HAAD) licensing for practice in Abu Dhabi and Northern Emirates.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 9,
    official_source_links: ['https://www.doh.gov.ae'], egypt_specific_notes: 'Similar PSV Dataflow process. Typically requires a written exam.' },
  { name: 'Qatar — QCHP', category: 'doctor', target_country: 'Qatar',
    description: 'Qatar Council for Healthcare Practitioners licensing — growing healthcare sector with World Cup legacy infrastructure.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 10,
    official_source_links: ['https://www.qchp.org.qa'], egypt_specific_notes: 'Prometric-based exam with dataflow verification.' },
  { name: 'Kuwait — MOH Licensing', category: 'doctor', target_country: 'Kuwait',
    description: 'Kuwait Ministry of Health licensing for medical practice — established destination for Egyptian doctors.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 11,
    official_source_links: [], egypt_specific_notes: 'Requires credential verification and Kuwait MOH written exam for some specialities.' },
  { name: 'Bahrain — NHRA', category: 'doctor', target_country: 'Bahrain',
    description: 'National Health Regulatory Authority licensing for medical practice in Bahrain.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 12,
    official_source_links: ['https://www.nhra.bh'], egypt_specific_notes: 'Smaller job market but faster processing times than Saudi/UAE.' },
  { name: 'Oman — MOH Licensing', category: 'doctor', target_country: 'Oman',
    description: 'Oman Ministry of Health licensing — emerging destination with growing healthcare investment.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 13,
    official_source_links: [], egypt_specific_notes: 'Prometric exam typically required. Growing demand for specialists.' },

  // ===== DOCTOR: EUROPE =====
  { name: 'UK — PLAB', category: 'doctor', target_country: 'United Kingdom',
    description: 'UK medical licensing via PLAB 1 and PLAB 2, then GMC registration — the most popular European route for Egyptian graduates.',
    required_exams: [
      { name: 'PLAB 1', official_link: 'https://www.gmc-uk.org', format: 'computer', cost_usd: 300, retake_policy: 'Max 4 attempts' },
      { name: 'PLAB 2', official_link: 'https://www.gmc-uk.org', format: 'practical', cost_usd: 1000, retake_policy: 'Max 4 attempts' },
    ],
    required_language_tests: [
      { language: 'English', test_name: 'IELTS', min_score: '7.5', official_link: 'https://www.ielts.org' },
      { language: 'English', test_name: 'OET Medicine', min_score: 'B', official_link: 'https://www.oet.com' },
    ],
    total_estimated_cost_usd: 4000, total_duration_months: 18,
    content_status: 'verified', order: 14,
    official_source_links: ['https://www.gmc-uk.org'], egypt_specific_notes: 'Egyptian MBBS recognized by GMC. Foundation year 2 (FY2) equivalence often required.' },
  { name: 'Ireland — IMC Registration', category: 'doctor', target_country: 'Ireland',
    description: 'Irish Medical Council registration via Certificate of Experience — growing destination with strong Egyptian doctor community.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 15,
    official_source_links: ['https://www.medicalcouncil.ie'], egypt_specific_notes: 'English-friendly. EU/EEA exemption issues affect non-EU graduates.' },
  { name: 'Germany — Approbation', category: 'doctor', target_country: 'Germany',
    description: 'German medical licensing (Approbation) — requires German B2/C1 proficiency, growing demand for international doctors.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 16,
    official_source_links: [], egypt_specific_notes: 'Language-gated (German B2/C1 required). EQF level verification and knowledge exam usually needed.' },
  { name: 'Malta — Medical Council Registration', category: 'doctor', target_country: 'Malta',
    description: 'Maltese medical licensing — smaller market with English-friendly environment and growing Egyptian presence.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 17,
    official_source_links: [], egypt_specific_notes: 'English is an official language. Generally faster process than UK/Germany.' },

  // ===== DOCTOR: NORTH AMERICA =====
  { name: 'USA — USMLE', category: 'doctor', target_country: 'USA',
    description: 'US medical licensing via USMLE Steps 1-3, plus ECFMG certification for IMGs — highest-stakes, highest-reward pathway.',
    required_exams: [
      { name: 'USMLE Step 1', official_link: 'https://www.usmle.org', format: 'computer', cost_usd: 1000, retake_policy: 'Max 3 attempts per year' },
      { name: 'USMLE Step 2 CK', official_link: 'https://www.usmle.org', format: 'computer', cost_usd: 1000, retake_policy: 'Max 3 attempts per year' },
      { name: 'USMLE Step 3', official_link: 'https://www.usmle.org', format: 'computer', cost_usd: 900, retake_policy: 'Max 3 attempts per year' },
    ],
    required_language_tests: [{ language: 'English', test_name: 'OET Medicine', min_score: '350', official_link: 'https://www.oet.com' }],
    total_estimated_cost_usd: 8000, total_duration_months: 36,
    content_status: 'verified', order: 18,
    official_source_links: ['https://www.usmle.org', 'https://www.ecfmg.org'], egypt_specific_notes: 'MBBS must be verified by ECFMG before Step 1. Egyptian graduates have high match rates in Internal Medicine and Pediatrics.' },
  { name: 'Canada — NAC/MCCQE', category: 'doctor', target_country: 'Canada',
    description: 'Canadian medical licensing via NAC-OSCE and MCCQE Part I — competitive but growing pathway for IMGs.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 19,
    official_source_links: ['https://www.mcc.ca'], egypt_specific_notes: 'Requires MCCQE Part I and NAC-OSCE. Practice-ready assessment programs available in some provinces.' },

  // ===== DOCTOR: OCEANIA =====
  { name: 'Australia — AMC', category: 'doctor', target_country: 'Australia',
    description: 'Australian Medical Council exams (AMC MCQ + clinical) — well-established route with strong job market for specialists.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 20,
    official_source_links: ['https://www.amc.org.au'], egypt_specific_notes: 'Competency Authority Pathway available for specialists with comparable training.' },
  { name: 'New Zealand — NZREX', category: 'doctor', target_country: 'New Zealand',
    description: 'New Zealand Registration Exam (NZREX) for IMGs — smaller market but streamlined pathway.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 21,
    official_source_links: ['https://www.mcnz.org.nz'], egypt_specific_notes: 'NZREX Clinical exam required. Competent Authority pathway available for some qualifications.' },

  // ===== DOCTOR: ADMIN/GLOBAL HEALTH =====
  { name: 'International Organization Track (WHO/UN)', category: 'doctor', target_country: 'Global/Multiple',
    description: 'Public health and policy roles with WHO, UNICEF, UNFPA, and other UN agencies — usually requires MPH or global health experience.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 22,
    official_source_links: ['https://www.who.int/careers'], egypt_specific_notes: 'Not exam-gated. Requires MPH, relevant experience, and UN language proficiency.' },
  { name: 'Humanitarian Field Track (MSF, IRC, Red Cross)', category: 'doctor', target_country: 'Global/Multiple',
    description: 'Field medical roles in humanitarian response — crisis medicine, emergency surgery, and public health in conflict/disaster zones.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 23,
    official_source_links: ['https://www.msf.org/work-msf'], egypt_specific_notes: 'Requires clinical experience, language skills (French/Arabic valuable), and willingness to work in insecure environments.' },
  { name: 'Global Health Research Track', category: 'doctor', target_country: 'Global/Multiple',
    description: 'Research positions with international universities and institutes — publication-driven, often PhD or MPH pathway.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 24,
    official_source_links: [], egypt_specific_notes: 'Research experience and publications are key. Often requires MPH, MSc, or PhD.' },
  { name: 'Health-Tech / Digital Health Industry Track', category: 'doctor', target_country: 'Global/Multiple',
    description: 'Clinical roles inside health-tech companies — telemedicine platforms, health AI, clinical decision support — growing alternative to classic migration.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 25,
    official_source_links: [], egypt_specific_notes: 'Remote-friendly. Clinical experience valued. Product management or informatics skills advantageous.' },
  { name: 'Pharmaceutical / Clinical Research Industry Track', category: 'doctor', target_country: 'Global/Multiple',
    description: 'Medical affairs, clinical research associate, or pharmacovigilance roles with multinational pharma — often Egypt/Gulf-based.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 26,
    official_source_links: [], egypt_specific_notes: 'Egypt and UAE are regional hubs for pharma companies. Clinical research experience and GCP certification valuable.' },

  // ===== NURSE: EGYPT NATIONAL TRACKS =====
  { name: 'Stay-Egypt (MOH Government Nursing Track)', category: 'nurse', target_country: 'Egypt',
    description: 'Ministry of Health hospital nursing placement — government salary scale with pension and job security.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 1,
    official_source_links: [], egypt_specific_notes: 'Requires Egyptian Nursing Syndicate registration. Government hospitals across all governorates.' },
  { name: 'Stay-Egypt (University/Teaching Hospital Nursing Track)', category: 'nurse', target_country: 'Egypt',
    description: 'Academic hospital nursing position with path toward nursing education and faculty roles.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 2,
    official_source_links: [], egypt_specific_notes: 'Typically requires Bachelor\'s in Nursing. Teaching hospitals in major cities (Cairo, Alexandria).' },
  { name: 'Stay-Egypt (Private Sector Nursing)', category: 'nurse', target_country: 'Egypt',
    description: 'Private hospital nursing in Egypt — generally higher pay than government but less job security.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 3,
    official_source_links: [], egypt_specific_notes: 'Private hospitals concentrated in Cairo, Alexandria, and tourist areas.' },
  { name: 'Stay-Egypt (Military/Police Nursing Services)', category: 'nurse', target_country: 'Egypt',
    description: 'Armed forces or police medical corps nursing track — distinct entry, benefits, and service commitment.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 4,
    official_source_links: [], egypt_specific_notes: 'Requires military/security clearance. Service commitment and benefits differ from civilian tracks.' },
  { name: 'Stay-Egypt (Postgraduate Nursing Track)', category: 'nurse', target_country: 'Egypt',
    description: 'Pursuing a Master\'s in Nursing or nursing specialization in Egypt as the next career step.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 5,
    official_source_links: [], egypt_specific_notes: 'Egyptian universities offer Master\'s in Nursing with clinical and thesis components.' },
  { name: 'Stay-Egypt (NGO/International Health Nursing)', category: 'nurse', target_country: 'Egypt',
    description: 'Working with international health organizations operating inside Egypt — WHO, UNICEF, UNFPA nursing programs.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 6,
    official_source_links: [], egypt_specific_notes: 'Relevant experience and English proficiency important. Contract-based, competitive positions.' },

  // ===== NURSE: GULF =====
  { name: 'Saudi Arabia — Saudi Nursing License (SCFHS)', category: 'nurse', target_country: 'Saudi Arabia',
    description: 'Saudi Commission for Health Specialties nursing licensing via Prometric — the largest overseas destination for Egyptian nurses.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 7,
    official_source_links: ['https://www.scfhs.org.sa'], egypt_specific_notes: 'Prometric exam for nursing. Dataflow verification required. Arabic language sometimes required for patient-facing roles.' },
  { name: 'UAE — Nursing License (DHA/DoH)', category: 'nurse', target_country: 'UAE',
    description: 'Dubai Health Authority or Department of Health Abu Dhabi licensing for nursing practice in the UAE.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 8,
    official_source_links: ['https://www.dha.gov.ae'], egypt_specific_notes: 'Primary Source Verification required. Written exam for licensing.' },

  // ===== NURSE: EUROPE =====
  { name: 'UK — NMC OSCE', category: 'nurse', target_country: 'United Kingdom',
    description: 'UK nursing registration via NMC — CBT + OSCE, the most popular European route for Egyptian nurses.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 9,
    official_source_links: ['https://www.nmc.org.uk'], egypt_specific_notes: 'IELTS 7.0 or OET B required. CBT followed by OSCE in UK. Growing NHS recruitment from Egypt.' },
  { name: 'Ireland — NMBI Registration', category: 'nurse', target_country: 'Ireland',
    description: 'Nursing and Midwifery Board of Ireland (NMBI) registration — English-friendly alternative to UK.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 10,
    official_source_links: ['https://www.nmbi.ie'], egypt_specific_notes: 'IELTS/OET requirement. Competency assessment and adaptation period may be required.' },
  { name: 'Germany — Nursing Approbation', category: 'nurse', target_country: 'Germany',
    description: 'German nursing licensing (Approbation) — requires German B1/B2, growing recruitment from Egypt.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 11,
    official_source_links: [], egypt_specific_notes: 'German B1/B2 certification required. Recognition procedure for foreign nursing qualifications.' },
  { name: 'Malta — Nursing Council Registration', category: 'nurse', target_country: 'Malta',
    description: 'Maltese nursing registration — English-friendly, smaller but accessible market.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 12,
    official_source_links: [], egypt_specific_notes: 'English language requirement. Smaller job market but faster process than UK/Germany.' },

  // ===== NURSE: NORTH AMERICA =====
  { name: 'Canada — NCLEX-RN', category: 'nurse', target_country: 'Canada',
    description: 'Canadian nursing licensing via NCLEX-RN, plus NNAS assessment for Internationally Educated Nurses (IENs).',
    required_exams: [
      { name: 'NCLEX-RN', official_link: 'https://www.ncsbn.org/nclex.htm', format: 'computer', cost_usd: 400, retake_policy: 'Max 8 attempts per year' },
      { name: 'Jurisprudence Exam', official_link: 'https://www.cno.org', format: 'online', cost_usd: 100, retake_policy: 'Unlimited' },
    ],
    required_language_tests: [{ language: 'English', test_name: 'IELTS Academic', min_score: '7.0', official_link: 'https://www.ielts.org' }],
    total_estimated_cost_usd: 5000, total_duration_months: 24,
    content_status: 'verified', order: 13,
    official_source_links: ['https://www.nnas.ca', 'https://www.cno.org'], egypt_specific_notes: 'NNAS assessment required for Egyptian nursing diplomas. Bridging programs often needed for clinical hours equivalence.' },
  { name: 'USA — NCLEX-RN', category: 'nurse', target_country: 'USA',
    description: 'US nursing licensing via NCLEX-RN — the highest-paying destination for Egyptian nurses.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 14,
    official_source_links: ['https://www.ncsbn.org/nclex.htm'], egypt_specific_notes: 'CGFNS or equivalent credentials evaluation required. VisaScreen certification needed for work visa.' },

  // ===== NURSE: OCEANIA =====
  { name: 'Australia — AHPRA/ANMAC Nursing', category: 'nurse', target_country: 'Australia',
    description: 'Australian nursing registration via AHPRA — skilled migration pathway with strong demand across all states.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 15,
    official_source_links: ['https://www.ahpra.gov.au'], egypt_specific_notes: 'ANMAC skills assessment required. IELTS 7.0 or OET B. Bridging programs may be needed.' },
  { name: 'New Zealand — Nursing Council Registration', category: 'nurse', target_country: 'New Zealand',
    description: 'New Zealand nursing registration — streamlined pathway for IENs with growing healthcare workforce needs.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 16,
    official_source_links: ['https://www.nursingcouncil.org.nz'], egypt_specific_notes: 'Competency assessment program (CAP) may be required. IELTS 7.0.' },

  // ===== NURSE: ADMIN/GLOBAL HEALTH =====
  { name: 'International Organization Nursing (WHO/UN)', category: 'nurse', target_country: 'Global/Multiple',
    description: 'Nursing advisory and program management roles with WHO, UNICEF, UNFPA — public health focus.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 17,
    official_source_links: ['https://www.who.int/careers'], egypt_specific_notes: 'MPH or relevant experience. Not exam-gated. Usually requires UN language proficiency.' },
  { name: 'Humanitarian Nursing (MSF, IRC, Red Cross)', category: 'nurse', target_country: 'Global/Multiple',
    description: 'Field nursing in humanitarian settings — emergency response, primary care, and public health in crisis zones.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 18,
    official_source_links: ['https://www.msf.org/work-msf'], egypt_specific_notes: 'Clinical experience, language skills, and willingness to work in insecure environments required.' },
  { name: 'Global Health Research Nursing', category: 'nurse', target_country: 'Global/Multiple',
    description: 'Research nursing roles with international health research institutes — clinical trials, epidemiological studies, and implementation research.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 19,
    official_source_links: [], egypt_specific_notes: 'Research nursing and GCP (Good Clinical Practice) certification valuable.' },
  { name: 'Health-Tech Nursing / Nursing Informatics', category: 'nurse', target_country: 'Global/Multiple',
    description: 'Clinical informatics and health-tech roles for nurses — EHR implementation, telehealth, and clinical product management.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 20,
    official_source_links: [], egypt_specific_notes: 'Informatics experience and EHR knowledge valuable. Remote-friendly career.' },
  { name: 'Pharmaceutical/Clinical Research Nursing', category: 'nurse', target_country: 'Global/Multiple',
    description: 'Clinical research nursing roles within pharmaceutical companies — clinical trial coordination and pharmacovigilance.',
    required_exams: [], required_language_tests: [], total_estimated_cost_usd: null, total_duration_months: null,
    content_status: 'stub', order: 21,
    official_source_links: [], egypt_specific_notes: 'GCP certification required. Regional pharma hubs in Egypt and UAE.' },
];
